// Code generated by "stringer -type=Command"; DO NOT EDIT.

package arithmetic

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Add-0]
	_ = x[Sub-1]
	_ = x[Neg-2]
	_ = x[EQ-3]
	_ = x[GT-4]
	_ = x[LT-5]
	_ = x[And-6]
	_ = x[Or-7]
	_ = x[Not-8]
	_ = x[Unknown-9]
}

const _Command_name = "AddSubNegEQGTLTAndOrNotUnknown"

var _Command_index = [...]uint8{0, 3, 6, 9, 11, 13, 15, 18, 20, 23, 30}

func (i Command) String() string {
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
